=== svedentsov/job4j/chapter_007/src/main/resources/xml/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:job="http://job4j.ru"
           targetNamespace="http://job4j.ru">

    <xs:element name="entries">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entry" type="job:entryType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="entryType">
        <xs:sequence>
            <xs:element type="xs:int" name="field"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== svedentsov/job4j/2_chapter_003/src/test/resources/xml/first.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entries xmlns="http://job4j.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://job4j.ru input.xsd" >
    <entry>
        <field>1</field>
    </entry>
    <entry>
        <field>2</field>
    </entry>
    <entry>
        <field>3</field>
    </entry>
    <entry>
        <field>4</field>
    </entry>
    <entry>
        <field>5</field>
    </entry>
</entries>
